{{- if and .Values.subnetRouter.enabled .Values.subnetRouter.authKey (not .Values.subnetRouter.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  {{- include "common.metadata" (dict "name" (printf "%s-subnet-router" (include "common.fullname" .)) "root" $) | nindent 2 }}
type: Opaque
stringData:
  auth-key: {{ .Values.subnetRouter.authKey | quote }}
{{- end }}
