{{- if .Values.subnetRouter.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "common.metadata" (dict "name" (printf "%s-subnet-router" (include "common.fullname" .)) "root" $) | nindent 2 }}
{{- end }}
