apiVersion: v2
name: qbittorrent
description: A Helm chart for qBittorrent - a free and open-source BitTorrent client
type: application
version: 1.0.0
appVersion: "5.0.4"
home: https://www.qbittorrent.org/
sources:
  - https://github.com/qbittorrent/qBittorrent
maintainers:
  - name: danilupion
    email: danilupion@gmail.com
keywords:
  - bittorrent
  - torrent
  - download
  - p2p

dependencies:
  - name: common
    version: 0.1.0
    repository: file://../../common
