apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "common.metadata" (dict "name" (include "common.fullname" .) "root" $) | nindent 2 }}
spec:
  replicas: 1
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" (dict "root" $ "component" "media-management") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" (dict "root" $ "component" "media-management") | nindent 8 }}
    spec:
      containers:
        - name: radarr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.radarr.port }}
              protocol: TCP
          env:
            {{- include "common.env" (dict "name" "PUID" "value" (.Values.linuxserver.puid | toString)) | nindent 12 }}
            {{- include "common.env" (dict "name" "PGID" "value" (.Values.linuxserver.pgid | toString)) | nindent 12 }}
            {{- include "common.env" (dict "name" "TZ" "value" .Values.linuxserver.tz) | nindent 12 }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            tcpSocket:
              port: {{ .Values.livenessProbe.tcpSocket.port }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            tcpSocket:
              port: {{ .Values.readinessProbe.tcpSocket.port }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.config.enabled }}
            - name: config
              mountPath: {{ .Values.persistence.config.mountPath }}
            {{- end }}
            {{- if .Values.storage.downloads.enabled }}
            - name: downloads
              mountPath: {{ .Values.storage.downloads.mountPath }}
              {{- with .Values.storage.downloads.subPath }}
              subPath: {{ . }}
              {{- end }}
            {{- end }}
            {{- if .Values.storage.movies.enabled }}
            - name: movies
              mountPath: {{ .Values.storage.movies.mountPath }}
              {{- with .Values.storage.movies.subPath }}
              subPath: {{ . }}
              {{- end }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.config.enabled }}
        - name: config
          {{- if .Values.persistence.config.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.config.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- if .Values.storage.downloads.enabled }}
        - name: downloads
          {{- if .Values.storage.downloads.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.storage.downloads.existingClaim }}
          {{- else if .Values.storage.downloads.hostPath }}
          hostPath:
            path: {{ .Values.storage.downloads.hostPath }}
            type: DirectoryOrCreate
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- if .Values.storage.movies.enabled }}
        - name: movies
          {{- if .Values.storage.movies.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.storage.movies.existingClaim }}
          {{- else if .Values.storage.movies.hostPath }}
          hostPath:
            path: {{ .Values.storage.movies.hostPath }}
            type: DirectoryOrCreate
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
