apiVersion: v2
name: homarr
description: Homarr - A modern homelab dashboard
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../../common"
