apiVersion: v2
name: filebrowser
description: Filebrowser - Web-based file manager
type: application
version: 0.1.0
appVersion: "2.31.2"

dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../../common"
