apiVersion: v2
name: dash
description: Dashdot - Modern server dashboard for smaller servers
type: application
version: 0.1.0
appVersion: "5.8.3"

dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../../common"
