apiVersion: v2
name: plex
description: Plex Media Server - Stream your media anywhere
type: application
version: 0.1.0
appVersion: "1.42.2"
dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../../common"
