apiVersion: v2
name: lidarr
description: Lidarr - Music collection manager for Usenet and BitTorrent users
type: application
version: 0.1.0
appVersion: "2.8.2"

dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../../common"
