apiVersion: v2
name: tautulli
description: Tautulli - Plex Media Server monitoring and statistics
type: application
version: 0.1.0
appVersion: "2.14.6"

dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../../common"
