apiVersion: v2
name: flaresolverr
description: FlareSolverr - Proxy server to bypass Cloudflare protection
type: application
version: 0.1.0
appVersion: "3.3.21"

dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../../common"
