apiVersion: v2
name: sonarr
description: Sonarr - TV series collection manager for Usenet and BitTorrent users
type: application
version: 0.1.0
appVersion: "4.0.16"

dependencies:
  - name: common
    version: 0.1.0
    repository: "file://../../common"
