apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "common.metadata" (dict "name" (include "common.fullname" .) "root" $) | nindent 2 }}
spec:
  replicas: 1
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" (dict "root" $ "component" "o11y") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" (dict "root" $ "component" "o11y") | nindent 8 }}
    spec:
      containers:
        - name: dash
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.privileged }}
          securityContext:
            privileged: true
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.dash.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.hostAccess.enabled }}
            - name: host
              mountPath: {{ .Values.hostAccess.mountPath }}
              readOnly: {{ .Values.hostAccess.readOnly }}
            {{- end }}
      volumes:
        {{- if .Values.hostAccess.enabled }}
        - name: host
          hostPath:
            path: /
        {{- end }}
