apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "common.metadata" (dict "name" (include "common.fullname" .) "root" $) | nindent 2 }}
spec:
  replicas: 1
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" (dict "root" $ "component" "tools") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.selectorLabels" (dict "root" $ "component" "tools") | nindent 8 }}
    spec:
      containers:
        - name: filebrowser
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.filebrowser.port }}
              protocol: TCP
          env:
            {{- include "common.env" (dict "name" "FB_PORT" "value" (toString .Values.filebrowser.port)) | nindent 12 }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.database.enabled }}
            - name: database
              mountPath: {{ .Values.persistence.database.mountPath }}
            {{- end }}
            {{- if .Values.persistence.data.enabled }}
            - name: data
              mountPath: {{ .Values.persistence.data.mountPath }}
              {{- with .Values.persistence.data.subPath }}
              subPath: {{ . }}
              {{- end }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.database.enabled }}
        - name: database
          {{- if .Values.persistence.database.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.database.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        {{- if .Values.persistence.data.enabled }}
        - name: data
          {{- if .Values.persistence.data.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
